const defaultBlendModeOrder = [
  'darken',
  'multiply',
  'linearBurn',
  'colorBurn',
  'darkerColor',
  'pinLight',
  'overlay',
  'linearLight',
  'vividLight',
  'softLight',
  'hardLight',
  'hardMix',
  'lighten',
  'screen',
  'linearDodge',
  'colorDodge',
  'lighterColor',
  'difference',
  'exclusion',
  'subtract',
  'divide',
  'hue',
  'color',
  'saturation',
  'luminosity',
] as const;

export default defaultBlendModeOrder;
