import { image01, image03 } from './tempImageData';

export const glAllLayerDataStateItem = [
  [
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `normal`,
        source: image01,
        originalWidth: 469,
        originalHeight: 463,
        mime: `image/jpeg`,
      },
      blendMode: `normal`,
      singleColor: null,
      layerNumber: 0,
      isBottomLayer: true,
    },
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `cover`,
        source: image03,
        originalWidth: 1024,
        originalHeight: 640,
        mime: `image/jpeg`,
      },
      blendMode: `overlay`,
      singleColor: null,
      layerNumber: 1,
      isBottomLayer: false,
    },
  ],
  [
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `normal`,
        source: image01,
        originalWidth: 469,
        originalHeight: 463,
        mime: `image/jpeg`,
      },
      blendMode: `normal`,
      singleColor: null,
      layerNumber: 0,
      isBottomLayer: true,
    },
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `cover`,
        source: image03,
        originalWidth: 1024,
        originalHeight: 640,
        mime: `image/jpeg`,
      },
      blendMode: `multiply`,
      singleColor: null,
      layerNumber: 1,
      isBottomLayer: false,
    },
  ],
  [
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `normal`,
        source: image01,
        originalWidth: 469,
        originalHeight: 463,
        mime: `image/jpeg`,
      },
      blendMode: `normal`,
      singleColor: null,
      layerNumber: 0,
      isBottomLayer: true,
    },
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `cover`,
        source: image03,
        originalWidth: 1024,
        originalHeight: 640,
        mime: `image/jpeg`,
      },
      blendMode: `screen`,
      singleColor: null,
      layerNumber: 1,
      isBottomLayer: false,
    },
  ],
  [
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `normal`,
        source: image01,
        originalWidth: 469,
        originalHeight: 463,
        mime: `image/jpeg`,
      },
      blendMode: `normal`,
      singleColor: null,
      layerNumber: 0,
      isBottomLayer: true,
    },
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `cover`,
        source: image03,
        originalWidth: 1024,
        originalHeight: 640,
        mime: `image/jpeg`,
      },
      blendMode: `colorDodge`,
      singleColor: null,
      layerNumber: 1,
      isBottomLayer: false,
    },
  ],
  [
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `normal`,
        source: image01,
        originalWidth: 469,
        originalHeight: 463,
        mime: `image/jpeg`,
      },
      blendMode: `normal`,
      singleColor: null,
      layerNumber: 0,
      isBottomLayer: true,
    },
    {
      name: `example`,
      type: `image`,
      opacity: 1.0,
      image: {
        type: `cover`,
        source: image03,
        originalWidth: 1024,
        originalHeight: 640,
        mime: `image/jpeg`,
      },
      blendMode: `colorBurn`,
      singleColor: null,
      layerNumber: 1,
      isBottomLayer: false,
    },
  ],
];

export default glAllLayerDataStateItem;
